name: Run Daily Task

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GSID: ${{ secrets.GSID }}

jobs:
  run-daily-task:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run daily check-in
      run: |
        python sign.py
